ignorePatterns:
  - 'node_modules/'
  - '*.md'
  - '*.env'

extends:
  - '@repo/shared-eslint-config'

overrides:
  - files:
      - "*.ts"
      - "!src/"
    parser: '@typescript-eslint/parser'
    rules:
      no-unused-vars: 'off'
      no-undef: 'off'
      '@typescript-eslint/no-unused-vars': 'off'

rules:
  no-redeclare: 'off'
  '@typescript-eslint/no-redeclare': 'error'
  '@typescript-eslint/explicit-function-return-type': 'off'
  '@typescript-eslint/no-explicit-any': 'off'
  'no-multi-spaces': 'error'
  'object-curly-spacing': ['error', 'always']
  'array-bracket-spacing': ['error', 'always']
