extends:
  - 'eslint-config-custom'

overrides:
  - files:
      - "*.ts"
      - "!src/"
    parser: '@typescript-eslint/parser'
    rules:
      no-unused-vars: 'off'
      no-undef: 'off'
      '@typescript-eslint/no-unused-vars': 'off'

rules:
  no-redeclare: 'off'
  '@typescript-eslint/no-redeclare': 'error'
  '@typescript-eslint/explicit-function-return-type': 'off'
  '@typescript-eslint/no-explicit-any': 'off'
